view:
  # 页面工程所在位置
  path: D:/git_repo/gitlab/group/vue-demo/dist/
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: view-server
  mvc:
    static-path-pattern: /**
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: true
    throw-exception-if-no-handler-found: true
    view:
      prefix:
      suffix: .html
  pid:
    file: ${spring.application.name}.pid
    fail-on-write-error: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    converters:
      preferred-json-mapper: jackson
  resources:
    add-mappings: true
    static-locations: file:${view.path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
logging:
  config: classpath:config/logback.xml
